id: P89748969
initial_creation_type: input
source_metadata:
  title: Bodhicaryāvatāra Series
  language: de
  description: 'Lotsawa House presents the following texts as part of its Bodhicaryāvatāra
    Series:'
  volume:
    9cc9e802a271498eb76355b592476044:
      title: 'Bodhicaryāvatāra—Chapter 1: The Benefits of Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    34112aa6b4c9408293b50043b04b313a:
      title: 'Bodhicaryāvatāra—Chapter 2: Confession of Negativity'
      parent: Bodhicaryāvatāra Root text
    b5f6214fce354556b0909ef521328f76:
      title: 'Bodhicaryāvatāra—Chapter 3: Fully Adopting Bodhicitta'
      parent: Bodhicaryāvatāra Root text
    1f4df269bbfb4c27b5c665c9ab905d7a:
      title: 'Bodhicaryāvatāra: Teachings and Overview'
      parent: Commentaries
    154980b744d8476b8e61986d5119fb65:
      title: Overview of the Bodhicaryāvatāra
      parent: Commentaries
    3f89608a92e14fce8a01c34cd4313af3:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Commentaries
    f859c226caa54456ac41707337b98ebf:
      title: 'The Garland of Jewel Ornaments: The Stages of Meditating on the Bodhicaryāvatāra'
      parent: Commentaries
    0d54cb0ccac7477095ea046bdd1c853a:
      title: Bodhicaryāvatāra Lineage Prayer
      parent: Lineage Prayers
    10e02c31181442a2810d9c7c8ec39208:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Lineage Prayers
    4cc7626a392f449fa44dd67e0edce940:
      title: 'Vines of Amṛta: A Prayer to the Lineage of the Bodhicaryāvatāra'
      parent: Lineage Prayers
created_at: '2022-03-01T03:02:08.555367'
last_modified_at: '2022-03-01T03:02:08.555370'
